// Shared dotloop-style template library: folders + every form PDF (served from
// /public/templates). Used by the Templates page and the loop document picker.

export type Template = {
  name: string;
  file: string;
  badge: string;
  pages: number;
  desc: string;
  folder: string;
  fillable?: boolean;
};

export // dotloop-style folder set (recreated for Foraker).
const FOLDERS: { id: string; label: string }[] = [
  { id: 'md-buying', label: 'MD Buying Docs' },
  { id: 'de-buying', label: 'DE Buying Docs' },
  { id: 'docspot', label: 'DOCSPOT' },
  { id: 'pa-buying', label: 'PA Buying Documents' },
  { id: 'pa-listing', label: 'PA Listing Documents' },
  { id: 'master', label: 'Foraker Realty Co Master Documents' },
  { id: 'listing-lease', label: 'Listing Lease Documents' },
  { id: 'lease', label: 'Lease Documents' },
  { id: 'onboarding', label: 'Agent Onboarding Documents' },
  { id: 'de-interactive', label: 'Delaware Interactive Forms' },
  { id: 'de-spanish', label: 'Delaware Spanish Translations' },
  { id: 'nar', label: 'NAR Guides & Resources' },
  { id: 'bright-mls', label: 'Bright MLS Interactive Documents' },
  { id: 'mar', label: 'MAR Interactive Forms' },
  { id: 'par', label: 'PAR Interactive Documents' },
  { id: 'md-rec', label: 'Maryland REC Interactive Forms' },
  { id: 'dar', label: 'DAR Interactive Forms' },
];

export const TEMPLATES: Template[] = [
  {
    name: 'Right to Farm (Cecil County)',
    file: 'md-right-to-farm-cecil.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'md-buying',
    desc: 'Cecil County, MD right-to-farm transfer disclosure.',
  },
  {
    name: 'Cecil County Hazardous Waste Sites Addendum',
    file: 'md-cecil-hazardous-waste.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'md-buying',
    desc: 'Cecil County, MD hazardous waste sites addendum.',
  },
  {
    name: 'Residential Contract of Sale (MAR)',
    file: 'md-residential-contract-mar.pdf',
    badge: 'MD',
    pages: 11,
    fillable: true,
    folder: 'md-buying',
    desc: 'Maryland REALTORS residential contract of sale.',
  },
  {
    name: 'Agreement of Sale for Delaware Residential Property',
    file: 'de-agreement-of-sale.pdf',
    badge: 'DE',
    pages: 10,
    fillable: true,
    folder: 'de-buying',
    desc: 'Delaware Association of REALTORS residential agreement of sale.',
  },
  {
    name: 'ICA \u2014 Foraker Realty Affiliation',
    file: 'ica-foraker-affiliation.pdf',
    badge: 'FRC',
    pages: 6,
    folder: 'docspot',
    desc: 'Independent Contractor Agreement \u2014 Foraker Realty Co affiliation.',
  },
  {
    name: 'Team Addendum to the Independent Contractor Agreement',
    file: 'team-addendum-ica.pdf',
    badge: 'FRC',
    pages: 3,
    folder: 'docspot',
    desc: 'Team addendum to the Foraker independent contractor agreement.',
  },
  {
    name: 'Protect Your Family From Lead in Your Home',
    file: 'protect-your-family-lead.pdf',
    badge: 'EPA',
    pages: 19,
    folder: 'pa-buying',
    desc: 'EPA lead-paint disclosure booklet.',
  },
  {
    name: 'Protect Your Family From Lead in Your Home',
    file: 'protect-your-family-lead.pdf',
    badge: 'EPA',
    pages: 19,
    folder: 'pa-listing',
    desc: 'EPA lead-paint disclosure booklet.',
  },
  {
    name: 'Protect Your Family From Lead in Your Home',
    file: 'protect-your-family-lead.pdf',
    badge: 'EPA',
    pages: 19,
    folder: 'listing-lease',
    desc: 'EPA lead-paint disclosure booklet.',
  },
  {
    name: 'Protect Your Family From Lead in Your Home',
    file: 'protect-your-family-lead.pdf',
    badge: 'EPA',
    pages: 19,
    folder: 'lease',
    desc: 'EPA lead-paint disclosure booklet.',
  },
  {
    name: 'Lead-Based Paint Hazards Disclosure (PAR LPH)',
    file: 'pa-lead-based-paint-hazards-disclosure.pdf',
    badge: 'PA',
    pages: 2,
    fillable: true,
    folder: 'pa-buying',
    desc: 'Pennsylvania Association of REALTORS lead-paint disclosure for properties built before 1978.',
  },
  {
    name: 'Lead-Based Paint Hazards Disclosure (PAR LPH)',
    file: 'pa-lead-based-paint-hazards-disclosure.pdf',
    badge: 'PA',
    pages: 2,
    fillable: true,
    folder: 'pa-listing',
    desc: 'Pennsylvania Association of REALTORS lead-paint disclosure for properties built before 1978.',
  },
  {
    name: 'Wire Fraud Notice (PAR WFN)',
    file: 'wire-fraud-notice.pdf',
    badge: 'PA',
    pages: 1,
    folder: 'pa-buying',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Wire Fraud Notice (PAR WFN)',
    file: 'wire-fraud-notice.pdf',
    badge: 'PA',
    pages: 1,
    folder: 'pa-listing',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Wire Fraud Notice (PAR WFN)',
    file: 'wire-fraud-notice.pdf',
    badge: 'PA',
    pages: 1,
    folder: 'listing-lease',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Wire Fraud Notice (PAR WFN)',
    file: 'wire-fraud-notice.pdf',
    badge: 'PA',
    pages: 1,
    folder: 'lease',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Buyer (Tenant) Agency Contract (PAR BAC)',
    file: 'buyer-tenant-agency-contract.pdf',
    badge: 'PA',
    pages: 4,
    fillable: true,
    folder: 'pa-buying',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Buyer (Tenant) Agency Contract (PAR BAC)',
    file: 'buyer-tenant-agency-contract.pdf',
    badge: 'PA',
    pages: 4,
    fillable: true,
    folder: 'lease',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: "Buyer's Estimated Costs and Deposit Money Notice",
    file: 'buyers-estimated-costs.pdf',
    badge: 'PA',
    pages: 1,
    folder: 'pa-buying',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Consumer Notice (PAR CN) - Buying',
    file: 'consumer-notice-cn-buying.pdf',
    badge: 'PA',
    pages: 2,
    folder: 'pa-buying',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Consumer Notice (PAR CNT) - Buying',
    file: 'consumer-notice-cnt-buying.pdf',
    badge: 'PA',
    pages: 2,
    folder: 'pa-buying',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: "Consumer's Guide to the Agreement of Sale",
    file: 'consumers-guide-agreement-of-sale.pdf',
    badge: 'PA',
    pages: 31,
    folder: 'pa-buying',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: "Consumer's Guide to the Agreement of Sale",
    file: 'consumers-guide-agreement-of-sale.pdf',
    badge: 'PA',
    pages: 31,
    folder: 'pa-listing',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Standard Agreement for the Sale of Real Estate (PAR ASR)',
    file: 'pa-standard-agreement-asr.pdf',
    badge: 'PA',
    pages: 14,
    fillable: true,
    folder: 'pa-buying',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Listing Contract (Seller Agency Contract)',
    file: 'pa-listing-contract-seller-agency.pdf',
    badge: 'PA',
    pages: 7,
    fillable: true,
    folder: 'pa-listing',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Property Description Sheet (PAR XLS-A)',
    file: 'property-description-sheet.pdf',
    badge: 'PA',
    pages: 2,
    folder: 'pa-listing',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: "Seller's Property Disclosure Statement (PAR SPD)",
    file: 'sellers-property-disclosure.pdf',
    badge: 'PA',
    pages: 11,
    folder: 'pa-listing',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Escrow Agreement for Earnest Money Deposit',
    file: 'escrow-agreement-earnest-money.pdf',
    badge: 'FRC',
    pages: 5,
    folder: 'master',
    desc: 'Foraker Realty Co document.',
  },
  {
    name: '24 Hr Showing / Touring Agreement',
    file: 'showing-touring-agreement.pdf',
    badge: 'FRC',
    pages: 1,
    folder: 'master',
    desc: 'Foraker Realty Co document.',
  },
  {
    name: 'Affiliated Business Agreement Disclosure',
    file: 'affiliated-business-disclosure.pdf',
    badge: 'FRC',
    pages: 2,
    folder: 'master',
    desc: 'Foraker Realty Co document.',
  },
  {
    name: 'Foraker Realty Co Important Acknowledgements',
    file: 'foraker-important-acknowledgements.pdf',
    badge: 'FRC',
    pages: 1,
    folder: 'master',
    desc: 'Foraker Realty Co document.',
  },
  {
    name: 'Listing for Rent Contract (Landlord Agency)',
    file: 'listing-for-rent-contract.pdf',
    badge: 'PA',
    pages: 5,
    fillable: true,
    folder: 'listing-lease',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Property Description Sheet for Rental (PAR XLS)',
    file: 'property-description-sheet-rental.pdf',
    badge: 'PA',
    pages: 2,
    folder: 'listing-lease',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Property Management Agreement (PAR PMA)',
    file: 'property-management-agreement.pdf',
    badge: 'PA',
    pages: 6,
    fillable: true,
    folder: 'listing-lease',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Rental Application for Landlord Agents (PAR R)',
    file: 'rental-application-landlord-agents.pdf',
    badge: 'PA',
    pages: 4,
    folder: 'listing-lease',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Residential Lease (PAR RL)',
    file: 'residential-lease.pdf',
    badge: 'PA',
    pages: 7,
    fillable: true,
    folder: 'listing-lease',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Residential Lease (PAR RL)',
    file: 'residential-lease.pdf',
    badge: 'PA',
    pages: 7,
    fillable: true,
    folder: 'lease',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Rental Application (PAR RA)',
    file: 'rental-application-ra.pdf',
    badge: 'PA',
    pages: 4,
    folder: 'lease',
    desc: 'Pennsylvania Association of REALTORS form.',
  },
  {
    name: 'Condominium Resale Disclosure and Transmittal',
    file: 'mar-condo-resale-disclosure-transmittal.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Condominium Resale Disclosure Certificate',
    file: 'mar-condo-resale-certificate.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Condominium Resale Notice',
    file: 'mar-condo-resale-notice.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Conventional Financing Addendum',
    file: 'mar-conventional-financing-addendum.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Escrow Agreement Between Buyer, Seller, and Escrow Agent',
    file: 'mar-escrow-agreement.pdf',
    badge: 'MD',
    pages: 3,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Exclusive Buyer/Tenant Representation Agreement',
    file: 'mar-exclusive-buyer-tenant-rep.pdf',
    badge: 'MD',
    pages: 5,
    fillable: true,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Exclusive Right to Sell Residential Brokerage Agreement',
    file: 'mar-exclusive-right-to-sell.pdf',
    badge: 'MD',
    pages: 10,
    fillable: true,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Exclusive Right to Sell Unimproved Land',
    file: 'mar-exclusive-right-to-sell-unimproved.pdf',
    badge: 'MD',
    pages: 9,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'FHA Financing Addendum',
    file: 'mar-fha-financing-addendum.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Foreign Investment in Real Property Tax Act',
    file: 'mar-foreign-investment-tax.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Maryland Homeowners Association Act Disclosures',
    file: 'mar-homeowners-assoc-disclosures.pdf',
    badge: 'MD',
    pages: 3,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Maryland Homeowners Association Act Notice',
    file: 'mar-homeowners-assoc-notice.pdf',
    badge: 'MD',
    pages: 3,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'National Priorities List (NPL) Superfund',
    file: 'mar-national-priorities-superfund.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'On-Site Sewage Disposal System (OSDS)',
    file: 'mar-on-site-sewage-disposal.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Owner Financing Contingency Addendum',
    file: 'mar-owner-financing-contingency.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Pet Rent Addendum',
    file: 'mar-pet-rent-addendum.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Maryland Residential Property Disclosure and Disclaimer',
    file: 'mar-residential-property-disclosure-disclaimer.pdf',
    badge: 'MD',
    pages: 4,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Resale of Condominium Unit Acknowledgment',
    file: 'mar-resale-condo-unit-acknowledgment.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: "Seller's Home of Choice Addendum",
    file: 'mar-sellers-home-of-choice.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Water Quality Test Addendum',
    file: 'mar-water-quality-test-addendum.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: 'Water Yield Test Notice',
    file: 'mar-water-yield-test-notice.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'mar',
    desc: 'Maryland REALTORS form.',
  },
  {
    name: "Auditor's Checklist and Reconciliation of Escrow",
    file: 'mrec-auditors-checklist.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: "Renters' Rights & Stabilization Act for Landlords",
    file: 'mrec-renters-rights-stabilization.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Residential Property Disclosure and Disclaimer',
    file: 'mar-residential-property-disclosure-disclaimer.pdf',
    badge: 'MD',
    pages: 4,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Addendum to Agreement of Sale',
    file: 'de-addendum-to-agreement-of-sale.pdf',
    badge: 'DE',
    pages: 1,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Addendum to Backup Agreement of Sale',
    file: 'de-addendum-to-backup-agreement-of-sale.pdf',
    badge: 'DE',
    pages: 13,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Agreement of Sale for Vacant Land / Agricultural Property',
    file: 'de-agreement-of-sale-for-vacant-land-agricultural.pdf',
    badge: 'DE',
    pages: 8,
    fillable: true,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Amendment to Exclusive Right to Sell Listing Agreement',
    file: 'de-amendment-to-exclusive-right-to-sell-listing-a.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Appraisal Gap Addendum',
    file: 'de-appraisal-gap-addendum.pdf',
    badge: 'DE',
    pages: 7,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'What is Bright MLS? (MLS Disclosure)',
    file: 'de-what-is-bright-mls-mls-disclosure.pdf',
    badge: 'DE',
    pages: 6,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Broker to Broker Referral Agreement',
    file: 'de-broker-to-broker-referral-agreement.pdf',
    badge: 'DE',
    pages: 9,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Contingency Waiver & Offer Acknowledgement',
    file: 'de-contingency-waiver-offer-acknowledgement.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'COVID-19 Related Delay Addendum',
    file: 'de-covid-19-related-delay-addendum.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'COVID-19 Release & Hold-Harmless Agreement',
    file: 'de-covid-19-release-hold-harmless-agreement.pdf',
    badge: 'DE',
    pages: 3,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'DUCIOA Resale Certification',
    file: 'de-ducioa-resale-certification.pdf',
    badge: 'DE',
    pages: 3,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Due Diligence Addendum',
    file: 'de-due-diligence-addendum.pdf',
    badge: 'DE',
    pages: 1,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Entry Agreement',
    file: 'de-entry-agreement.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Escalation Clause Addendum',
    file: 'de-escalation-clause-addendum.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Exclusive Buyer/Tenant Agency (Representation) Agreement',
    file: 'de-exclusive-buyer-tenant-agency-representation-a.pdf',
    badge: 'DE',
    pages: 4,
    fillable: true,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Exclusive Right to Sell Listing Agreement',
    file: 'de-exclusive-right-to-sell-listing-agreement.pdf',
    badge: 'DE',
    pages: 15,
    fillable: true,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Delaware Form REW-EST (Real Estate Tax Return)',
    file: 'de-delaware-form-rew-est-real-estate-tax-return.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Delaware Residential Landlord-Tenant Code (Summary)',
    file: 'de-delaware-residential-landlord-tenant-code-summ.pdf',
    badge: 'DE',
    pages: 10,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Reservation of Rights Addendum',
    file: 'de-reservation-of-rights-addendum.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Disclosure of Information on Lead-Based Paint (DE)',
    file: 'de-disclosure-of-information-on-lead-based-paint.pdf',
    badge: 'DE',
    pages: 3,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Modification to Exclusive Right to Sell Listing Agreement',
    file: 'de-modification-to-exclusive-right-to-sell-listin.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Must Sell Addendum',
    file: 'de-must-sell-addendum.pdf',
    badge: 'DE',
    pages: 3,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Mutual Release from Agreement of Sale',
    file: 'de-mutual-release-from-agreement-of-sale.pdf',
    badge: 'DE',
    pages: 1,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Pet Addendum',
    file: 'de-pet-addendum.pdf',
    badge: 'DE',
    pages: 1,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Pre-Settlement Inspection Acknowledgement',
    file: 'de-pre-settlement-inspection-acknowledgement.pdf',
    badge: 'DE',
    pages: 1,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Protect Your Family From Lead in Your Home',
    file: 'de-protect-your-family-from-lead-in-your-home.pdf',
    badge: 'EPA',
    pages: 20,
    folder: 'dar',
    desc: 'EPA lead-paint disclosure booklet.',
  },
  {
    name: 'Purchase Money Mortgage Addendum',
    file: 'de-purchase-money-mortgage-addendum.pdf',
    badge: 'DE',
    pages: 3,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'REALTORS & Attorneys Data Sheet',
    file: 'de-realtors-attorneys-data-sheet.pdf',
    badge: 'DE',
    pages: 1,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Repair and Maintenance Agreement',
    file: 'de-repair-and-maintenance-agreement.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Residential Lease-Rental Agreement',
    file: 'de-residential-lease-rental-agreement.pdf',
    badge: 'DE',
    pages: 6,
    fillable: true,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Seller Contribution Addendum',
    file: 'de-seller-contribution-addendum.pdf',
    badge: 'DE',
    pages: 1,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: "Seller's Disclosure and Radon Disclosure Exemption",
    file: 'de-seller-s-disclosure-and-radon-disclosure-exemp.pdf',
    badge: 'DE',
    pages: 3,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: "Seller's Disclosure of Real Property Condition Report",
    file: 'de-sellers-disclosure-real-property-condition.pdf',
    badge: 'DE',
    pages: 10,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: "Seller's Disclosure of Real Property Condition \u2014 New Construction Only",
    file: 'de-sellers-disclosure-new-construction.pdf',
    badge: 'DE',
    pages: 8,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: "Seller's Disclosure of Real Property Condition \u2014 Vacant Land (Residential Use)",
    file: 'de-sellers-disclosure-vacant-land.pdf',
    badge: 'DE',
    pages: 6,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: "Seller's Reaffirmation of Seller's Disclosure",
    file: 'de-seller-s-reaffirmation-of-seller-s-disclosure.pdf',
    badge: 'DE',
    pages: 3,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Short Sale and REO Acknowledgement',
    file: 'de-short-sale-and-reo-acknowledgement.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Delaware Manufactured Home Lot Lease \u2014 Tenant Rights (DOJ)',
    file: 'de-delaware-manufactured-home-lot-lease-tenant-ri.pdf',
    badge: 'DE',
    pages: 36,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Utility Addendum',
    file: 'de-utility-addendum.pdf',
    badge: 'DE',
    pages: 2,
    folder: 'dar',
    desc: 'Delaware Association of REALTORS form.',
  },
  {
    name: 'Tenants Bill of Rights — Amharic (MREC)',
    file: 'mrec-tenants-bill-of-rights-amharic.pdf',
    badge: 'MD',
    pages: 13,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Arabic (MREC)',
    file: 'mrec-tenants-bill-of-rights-arabic.pdf',
    badge: 'MD',
    pages: 13,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Burmese (MREC)',
    file: 'mrec-tenants-bill-of-rights-burmese.pdf',
    badge: 'MD',
    pages: 24,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Chinese (MREC)',
    file: 'mrec-tenants-bill-of-rights-chinese.pdf',
    badge: 'MD',
    pages: 14,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Dari (MREC)',
    file: 'mrec-tenants-bill-of-rights-dari.pdf',
    badge: 'MD',
    pages: 13,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — English (MREC)',
    file: 'mrec-tenants-bill-of-rights-english.pdf',
    badge: 'MD',
    pages: 14,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — French (MREC)',
    file: 'mrec-tenants-bill-of-rights-french.pdf',
    badge: 'MD',
    pages: 16,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Haitian Creole (MREC)',
    file: 'mrec-tenants-bill-of-rights-haitian-creole.pdf',
    badge: 'MD',
    pages: 15,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Korean (MREC)',
    file: 'mrec-tenants-bill-of-rights-korean.pdf',
    badge: 'MD',
    pages: 15,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Pashto (MREC)',
    file: 'mrec-tenants-bill-of-rights-pashto.pdf',
    badge: 'MD',
    pages: 14,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Russian (MREC)',
    file: 'mrec-tenants-bill-of-rights-russian.pdf',
    badge: 'MD',
    pages: 18,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Spanish (MREC)',
    file: 'mrec-tenants-bill-of-rights-spanish.pdf',
    badge: 'MD',
    pages: 15,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Swahili (MREC)',
    file: 'mrec-tenants-bill-of-rights-swahili.pdf',
    badge: 'MD',
    pages: 16,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Tagalog (MREC)',
    file: 'mrec-tenants-bill-of-rights-tagalog.pdf',
    badge: 'MD',
    pages: 17,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Tigrinya (MREC)',
    file: 'mrec-tenants-bill-of-rights-tigrinya.pdf',
    badge: 'MD',
    pages: 14,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Ukrainian (MREC)',
    file: 'mrec-tenants-bill-of-rights-ukrainian.pdf',
    badge: 'MD',
    pages: 17,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Urdu (MREC)',
    file: 'mrec-tenants-bill-of-rights-urdu.pdf',
    badge: 'MD',
    pages: 14,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Tenants Bill of Rights — Vietnamese (MREC)',
    file: 'mrec-tenants-bill-of-rights-vietnamese.pdf',
    badge: 'MD',
    pages: 16,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Consent for Dual Agency (MREC)',
    file: 'mrec-consent-for-dual-agency.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Home Buyer Tips for Choosing a Real Estate Agent (MREC)',
    file: 'mrec-home-buyer-tips.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Home Seller Tips for Choosing a Real Estate Agent (MREC)',
    file: 'mrec-home-seller-tips.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Notification of Dual Agency Within a Team (MREC)',
    file: 'mrec-notification-dual-agency-team.pdf',
    badge: 'MD',
    pages: 2,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'Source of Income Discrimination Laws in Maryland (MREC)',
    file: 'mrec-source-of-income-discrimination.pdf',
    badge: 'MD',
    pages: 1,
    folder: 'md-rec',
    desc: 'Maryland Real Estate Commission form.',
  },
  {
    name: 'NAR Consumer Guide: 10 Tips for Packing Smartly for a Move',
    file: 'nar-10-tips-for-packing-smartly-for-a-move.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: 10 Tips for Unpacking Smartly After a Move',
    file: 'nar-10-tips-for-unpacking-smartly-after-a-move.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: 5 Home Selling Tips for Privacy and Safety',
    file: 'nar-5-home-selling-tips-for-privacy-and-safety.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: 8 Tips for Selling Your Home in Winter',
    file: 'nar-8-tips-for-selling-your-home-in-winter.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Agency and Non-agency Relationships',
    file: 'nar-agency-and-non-agency-relationships.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Alternative Listing Options',
    file: 'nar-alternative-listing-options.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Are You Ready to Invest in Real Estate?',
    file: 'nar-are-you-ready-to-invest-in-real-estate.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Assistance Programs',
    file: 'nar-assistance-programs.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Buyer’s vs Seller’s Markets',
    file: 'nar-buyer-s-vs-seller-s-markets.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Buying Land and Building a New Home',
    file: 'nar-buying-land-and-building-a-new-home.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Buying Your First Home',
    file: 'nar-buying-your-first-home.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Buying a Historic Property',
    file: 'nar-buying-a-historic-property.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Can’t Pay Your Mortgage? You Have Options',
    file: 'nar-can-t-pay-your-mortgage-you-have-options.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Deeds and Titles',
    file: 'nar-deeds-and-titles.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Do You Need Private Mortgage Insurance?',
    file: 'nar-do-you-need-private-mortgage-insurance.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Escrow and Earnest Money',
    file: 'nar-escrow-and-earnest-money.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Fair Housing',
    file: 'nar-fair-housing.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Financing a Renovation When You Buy',
    file: 'nar-financing-a-renovation-when-you-buy.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Fire Damage and Policy Coverage',
    file: 'nar-fire-damage-and-policy-coverage.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Flood Insurance',
    file: 'nar-flood-insurance.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Hiring a Remodeling Contractor',
    file: 'nar-hiring-a-remodeling-contractor.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Home Inspections',
    file: 'nar-home-inspections.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Homeowners Associations',
    file: 'nar-homeowners-associations.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Homeowners Insurance',
    file: 'nar-homeowners-insurance.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: How to Make Your Home More Energy Efficient',
    file: 'nar-how-to-make-your-home-more-energy-efficient.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: How to Protect',
    file: 'nar-how-to-protect.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Listing Agreements',
    file: 'nar-listing-agreements.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Making Your Home More Energy Efficient',
    file: 'nar-making-your-home-more-energy-efficient.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Marketing Your Home',
    file: 'nar-marketing-your-home.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Mortgage Interest Tax Deduction',
    file: 'nar-mortgage-interest-tax-deduction.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Mortgages and Financing',
    file: 'nar-mortgages-and-financing.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Multiple Listing Services',
    file: 'nar-multiple-listing-services.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Navigating Mortgage Interest Rate Shifts',
    file: 'nar-navigating-mortgage-interest-rate-shifts.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Navigating Multiple Offers',
    file: 'nar-navigating-multiple-offers.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Negotiating Written Buyer Agreements',
    file: 'nar-negotiating-written-buyer-agreements.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Offers of Compensation',
    file: 'nar-offers-of-compensation.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Open Houses and Written Agreements',
    file: 'nar-open-houses-and-written-agreements.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Overcoming Barriers to Homeownership',
    file: 'nar-overcoming-barriers-to-homeownership.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Overcoming Roadblocks to a Sale or Purchase',
    file: 'nar-overcoming-roadblocks-to-a-sale-or-purchase.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Preparing for Homeownership',
    file: 'nar-preparing-for-homeownership.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Preparing to Sell Your Home',
    file: 'nar-preparing-to-sell-your-home.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Property Taxes',
    file: 'nar-property-taxes.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Real Estate Auctions',
    file: 'nar-real-estate-auctions.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Real Estate Contract Contingencies',
    file: 'nar-real-estate-contract-contingencies.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Realtors’® Duty to Put Client Interests Above Their Own',
    file: 'nar-realtors-duty-to-put-client-interests-above-their-own.pdf',
    badge: 'NAR',
    pages: 2,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Seller Concessions',
    file: 'nar-seller-concessions.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Seller Disclosures',
    file: 'nar-seller-disclosures.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Spotting Deepfake Scams in Real Estate',
    file: 'nar-spotting-deepfake-scams-in-real-estate.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Staging Your House for a Sale',
    file: 'nar-staging-your-house-for-a-sale.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: State and Local Tax (salt) Deductions',
    file: 'nar-state-and-local-tax-salt-deductions.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Steps Between Signing and Closing on a Home',
    file: 'nar-steps-between-signing-and-closing-on-a-home.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Ten Questions to Ask a Buyer’s Agent',
    file: 'nar-ten-questions-to-ask-a-buyer-s-agent.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Ten Questions to Ask a Seller’s Agent',
    file: 'nar-ten-questions-to-ask-a-seller-s-agent.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: The Appraisal Process',
    file: 'nar-the-appraisal-process.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Thinking of Selling? 7 Factors to Consider',
    file: 'nar-thinking-of-selling-7-factors-to-consider.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Understanding & Protecting Yourself from Title Fraud',
    file: 'nar-understanding-protecting-yourself-from-title-fraud.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Understanding Condo Ownership',
    file: 'nar-understanding-condo-ownership.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: What Goes into Pricing Your Home',
    file: 'nar-what-goes-into-pricing-your-home.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: What Is the VA Home Loan Guaranty?',
    file: 'nar-what-is-the-va-home-loan-guaranty.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: What Veterans Need to Know About Buying a Home',
    file: 'nar-what-veterans-need-to-know-about-buying-a-home.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Why Am I Being Asked to Sign a Written Buyer Agreement?',
    file: 'nar-why-am-i-being-asked-to-sign-a-written-buyer-agreement.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Working with a Real Estate Attorney',
    file: 'nar-working-with-a-real-estate-attorney.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Consumer Guide: Your Home and Estate Planning',
    file: 'nar-your-home-and-estate-planning.pdf',
    badge: 'NAR',
    pages: 1,
    folder: 'nar',
    desc: 'National Association of REALTORS consumer guide.',
  },
  {
    name: 'NAR Member Resource: Do\'s and Don\'ts When Working with Buyers',
    file: 'nar-dos-and-don-ts-when-working-with-buyers.pdf',
    badge: 'NAR',
    pages: 3,
    folder: 'nar',
    desc: 'National Association of REALTORS member resource.',
  },
  {
    name: 'NAR Member Resource: Do\'s and Don\'ts When Working with Sellers',
    file: 'nar-dos-and-don-ts-when-working-with-sellers.pdf',
    badge: 'NAR',
    pages: 3,
    folder: 'nar',
    desc: 'National Association of REALTORS member resource.',
  },
];
